### ISSUE TITLE
Ability to specify filetype, os type, bitness and latest on CLI

### ISSUE THREAD

**Issue by riesgo** [csek06/appd-binary-downloader#53]
Hello,

Would like the ability to download a specific artifact by specifying additional options of **OS type** + **bitness** + **filetype** + make sure it's the **latest** version using command line options.

For example:
./appd-downloader_linux -detect-host -ma
gives two options:
Which binary to download?
0: id: 17755 version:20.5.1.2635 title:Machine Agent Bundle - 64-bit linux (zip) (2020-05-29T21:53:02.902956Z)
1: id: 17753 version:20.5.1.2635 title:Machine Agent Bundle - 64-bit linux (rpm) (2020-05-29T21:52:56.200758Z)

I want zip version from that list.

**Comment by csek06** [comment]
With the latest update you can now use either of the following to get your intended results
./appd-downloader_linux -detect-host -ma -extension=zip
or
./appd-downloader_linux -ma -tos=linux -tbit=64 -extension=zip
